version: '3'

services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile 
    image: astro_reputebee
    container_name: astro_reputebee
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start
    tty: true #https://github.com/evanw/esbuild/issues/1848
